version: '3' 



services:
  ubuntu-ftp:
    image: ubuntu:24.04
    container_name: ubuntu-ftp-server
    ports:
      - "21:21"
      - "20:20"
      - "21100-21110:21100-21110"
    volumes:
      - ./ftp_data:/home/ftpuser
    environment:
      - FTP_USER=ftpuser
      - FTP_PASS=P@ssw0rd!
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y vsftpd && 
        echo 'ftpuser:12341234' | chpasswd && 
        useradd -m ftpuser && 
        echo 'local_enable=YES' >> /etc/vsftpd.conf && 
        echo 'write_enable=YES' >> /etc/vsftpd.conf && 
        echo 'chroot_local_user=YES' >> /etc/vsftpd.conf && 
        echo 'allow_writeable_chroot=YES' >> /etc/vsftpd.conf && 
        echo 'pasv_enable=YES' >> /etc/vsftpd.conf && 
        echo 'pasv_min_port=21100' >> /etc/vsftpd.conf && 
        echo 'pasv_max_port=21110' >> /etc/vsftpd.conf && 
        mkdir -p /home/ftpuser && 
        chown ftpuser:ftpuser /home/ftpuser && 
        /usr/sbin/vsftpd
      "